apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
 name: "prevent-default-json-read"
spec:
 kprobes:
 - call: "security_file_permission"
   syscall: false
   return: true
   args:
   - index: 0
     type: "file"
   - index: 1
     type: "int"
   returnArg:
     index: 0
     type: "int"
   returnArgAction: "Post"
   selectors:
   - matchArgs:     
     - index: 0
       operator: "Equal"
       values:
       - "/default.json"
     - index: 1
       operator: "Equal"
       values:
       - "4" # MAY_READ
     matchActions:
     - action: Sigkill
