apiVersion: "cilium.io/v1alpha1"
kind: TracingPolicy
metadata:
  name: "detect-container-breakout"
spec:
  kprobes:
    - call: "do_mount"
      syscall: true
      action: "Trace"
    - call: "do_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/proc/self/exe"
                - "/proc/sysrq-trigger"
      action: "Trace"
