apiVersion: "cilium.io/v1alpha1"
kind: TracingPolicy
metadata:
  name: "prevent-process-injection"
spec:
  kprobes:
    - call: "sys_ptrace"
      syscall: true
      action: "Deny"
    - call: "sys_process_vm_writev"
      syscall: true
      action: "Deny"
