apiVersion: "cilium.io/v1alpha1"
kind: TracingPolicy
metadata:
  name: "block-reverse-shell"
spec:
  kprobes:
    - call: "sys_execve"  # Changed from do_execve to execve
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/bin/sh"
          matchActions:
            - action: Sigkill
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/usr/bin/sh"
          matchActions:
            - action: Sigkill
        
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/usr/bin/curl"
          matchActions:
            - action: Sigkill
